# Generated by Django 5.0.2 on 2024-02-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuário',
            new_name='Usuario',
        ),
    ]
